version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: $MYSQL_NAME
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - $MYSQL_DATA_PATH:$MYSQL_CONTAINER_DATA_PATH
      - $MYSQL_CONF:$MYSQL_CONTAINER_CONF:ro
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ENV_MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_ENV_MYSQL_MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_ENV_MYSQL_MYSQL_PASSWORD
    networks:
      - dbtoes
  canal:
    image: canal/canal-server:v1.1.5
    container_name: $CANAL_CONTAINER_NAME
    ports:
      - 11110:11110
      - 11111:11111
      - 11112:11112
    volumes:
      - $CANAL_CONF:$CANAL_CONTAINER_CONF
    networks:
      - dbtoes
  canal-admin:
    image: canal/canal-admin:v1.1.5
    container_name: $CANAL_ADMIN_CONTAINER_NAME
    ports:
      - 3306:3306
      - 8089:8089
    volumes:
      - $CANAL_ADMIN_CONF:$CANAL_ADMIN_CONTAINER_CONF
      - $CANAL_ADMIN_ADMIN_DATA:$CANAL_ADMIN_CONTAINER_ADMIN_DATA
    networks:
      - dbtoes
  elasticsearch:
    image: elasticsearch:7.17.13
    container_name: $ELASTICSEARCH_CONTAINER_NAME
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
    networks:
      - dbtoes
  kibana:
    image: kibana:7.17.13
    container_name: $KIBANA_CONTAINER_NAME
    ports:
      - 5601:5601
    networks:
      - dbtoes
  rocketmq:
    image: apache/rocketmq:5.1.3
    container_name: $ROCKETMQ_CONTAINER_NAME
    ports:
      - 9876:9876
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - $ROCKETMQ_CONF:$ROCKETMQ_CONTAINER_CONF
      - $ROCKETMQ_DATA:$ROCKETMQ_CONTAINER_DATA
      - $ROCKETMQ_START_SHELL:$ROCKETMQ_CONTAINER_START_SHELL
    entrypoint:
      - bash
      - -c
      - $ROCKETMQ_CONTAINER_START_SHELL
    networks:
      - dbtoes
  rocketmq-dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: $ROCKETMQ_UI_CONTAINER_NAME
    environment:
      - "JAVA_OPTS=-Drocketmq.namesrv.addr=qslrocketmq:9876"
    ports:
      - 8080:8080
    networks:
      - dbtoes
networks:
  dbtoes:
    driver: bridge
